### PR TITLE
Add Archlinux AUR.

### PR DESCRIPTION
**Pull request by YangtseSu**

### CODE REVIEW

**Comment by dyc3** [comment]
Thanks for your interest. Would you mind explaining how exactly the AUR works? How will `steamguard-cli-git` update in the AUR when I make changes here or create a new release?

**Comment by YangtseSu** [comment]
Find information here:https://wiki.archlinux.org/index.php/Arch_User_Repository
AUR is a set of scripts to help Archlinux user install unofficial package. 

I wrote this "https://aur.archlinux.org/packages/steamguard-cli-git/"(You can look into the script file by click "View PKGBUILD")
Archlinux usr can use this command to install steamguard-cli (git version)
 $yaourt -S steamguard-git



No matter what you do, these will not be affected, they are just an automated script.

**Comment by YangtseSu** [comment]
This package will always be up to date,Because I use the git version.

**Comment by dyc3** [comment]
Ah, ok. I looked at the PKGBUILD script and it looks like the version number is hard coded. Is there a way we could get around that?

**Comment by YangtseSu** [comment]
It is auto config.By this function:
pkgver () {
  cd $_gitname
  git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

**Comment by dyc3** [comment]
Oh. I was looking at the line `pkgver=0.3.2.0.r1.g8c11d22`.

**Comment by dyc3** [comment]
Looking at the comments on the AUR, and somebody mentioned that `SteamAuth.dll` doesn't need to be executable. I'm going to look into that soon.

**Comment by dyc3** [comment]
Could you add me as a co-maintainer to the AUR package?

**Comment by YangtseSu** [comment]
Yes, of course. Your user name  is required.

**Comment by dyc3** [comment]
"dyc3", same as here. Thanks!

**Comment by YangtseSu** [comment]
Done

**Pull request merged**
